import random

questions = {
    "ar": {
        "sports": {
            "easy": [
                {"q": "كم لاعباً في فريق كرة القدم؟", "options": ["9", "10", "11", "12"], "answer": "11"},
                {"q": "في أي دولة أقيمت كأس العالم 2022؟", "options": ["الإمارات", "قطر", "السعودية", "البحرين"], "answer": "قطر"},
                {"q": "كم دقيقة يستغرق مباراة كرة القدم؟", "options": ["80", "90", "100", "120"], "answer": "90"},
                {"q": "ما اسم بطولة كرة القدم الأوروبية الأكبر للأندية؟", "options": ["الدوري الأوروبي", "دوري الأبطال", "كأس العالم للأندية", "السوبر الأوروبي"], "answer": "دوري الأبطال"},
                {"q": "كم مرة تلتقي الفرق في الدوري ذهاباً وإياباً؟", "options": ["مرة", "مرتين", "3 مرات", "4 مرات"], "answer": "مرتين"},
                {"q": "ما الرياضة التي تُلعب في ويمبلدون؟", "options": ["الغولف", "التنس", "الكريكيت", "الرغبي"], "answer": "التنس"},
                {"q": "كم طول ملعب كرة القدم الرسمي تقريباً؟", "options": ["80م", "90م", "100م", "105م"], "answer": "105م"},
                {"q": "ما الرياضة التي يستخدم فيها المضمار البيضاوي؟", "options": ["كرة القدم", "ألعاب القوى", "السباحة", "الجمباز"], "answer": "ألعاب القوى"},
                {"q": "كم عدد لاعبي كرة السلة في الملعب لكل فريق؟", "options": ["4", "5", "6", "7"], "answer": "5"},
                {"q": "ما طول الشبكة في كرة الطائرة؟", "options": ["2.24م", "2.43م", "2.60م", "3.00م"], "answer": "2.43م"},
            ],
            "medium": [
                {"q": "من فاز بكأس العالم 2018؟", "options": ["ألمانيا", "البرازيل", "فرنسا", "الأرجنتين"], "answer": "فرنسا"},
                {"q": "كم مرة فازت البرازيل بكأس العالم؟", "options": ["3", "4", "5", "6"], "answer": "5"},
                {"q": "من هو أكثر لاعب تسجيلاً للأهداف في تاريخ كرة القدم؟", "options": ["رونالدو", "ميسي", "بيليه", "مارادونا"], "answer": "رونالدو"},
                {"q": "من فاز بدوري أبطال أوروبا 2023؟", "options": ["ريال مدريد", "مانشستر سيتي", "برشلونة", "بايرن"], "answer": "مانشستر سيتي"},
                {"q": "كم هدفاً سجل رونالدو في مسيرته الدولية حتى 2023؟", "options": ["110", "118", "122", "130"], "answer": "118"},
                {"q": "أي بلد فازت بكأس العالم للسيدات أكثر مرة؟", "options": ["ألمانيا", "البرازيل", "الولايات المتحدة", "اليابان"], "answer": "الولايات المتحدة"},
                {"q": "من هو مدرب المنتخب الفرنسي الذي فاز بكأس العالم 2018؟", "options": ["زيدان", "ديشان", "هنري", "بلان"], "answer": "ديشان"},
                {"q": "أي نادٍ يلقب بـ الملكي؟", "options": ["برشلونة", "ريال مدريد", "يوفنتوس", "بايرن"], "answer": "ريال مدريد"},
                {"q": "ما اسم الدوري الإنجليزي الممتاز؟", "options": ["La Liga", "Serie A", "Premier League", "Bundesliga"], "answer": "Premier League"},
                {"q": "كم مرة فاز ليفربول بدوري أبطال أوروبا؟", "options": ["4", "5", "6", "7"], "answer": "6"},
            ],
            "hard": [
                {"q": "في أي عام تأسس نادي ريال مدريد؟", "options": ["1900", "1902", "1905", "1910"], "answer": "1902"},
                {"q": "من فاز بالكرة الذهبية أكثر مرة؟", "options": ["رونالدو", "ميسي", "نيمار", "مبابي"], "answer": "ميسي"},
                {"q": "كم عدد الفرق المشاركة في كأس العالم 2026؟", "options": ["32", "36", "48", "64"], "answer": "48"},
                {"q": "من سجل هدف اليد الشهير في كأس العالم؟", "options": ["بيليه", "رونالدو", "مارادونا", "زيدان"], "answer": "مارادونا"},
                {"q": "في أي عام بدأ دوري أبطال أوروبا بشكله الحالي؟", "options": ["1990", "1992", "1995", "1998"], "answer": "1992"},
                {"q": "من هو أصغر لاعب يسجل في كأس العالم؟", "options": ["بيليه", "رونالدو", "ميسي", "مبابي"], "answer": "بيليه"},
                {"q": "ما اسم ملعب برشلونة الجديد؟", "options": ["كامب نو", "إسبانيول", "أولمبيك", "سبوتيفاي كامب نو"], "answer": "سبوتيفاي كامب نو"},
                {"q": "كم هدفاً سجل غيرد مولر في مسيرته مع بايرن؟", "options": ["365", "398", "442", "520"], "answer": "442"},
                {"q": "أي منتخب لم يخسر قط في دور المجموعات بكأس العالم؟", "options": ["البرازيل", "ألمانيا", "إيطاليا", "إسبانيا"], "answer": "البرازيل"},
                {"q": "من هو حارس المرمى الأكثر مشاركة في تاريخ كأس العالم؟", "options": ["كاسياس", "بوفون", "نوير", "زوف"], "answer": "بوفون"},
            ],
        },
        "movies": {
            "easy": [
                {"q": "من أخرج فيلم Titanic؟", "options": ["ستيفن سبيلبرغ", "جيمس كاميرون", "كريستوفر نولان", "تيم بيرتون"], "answer": "جيمس كاميرون"},
                {"q": "ما اسم البطل في سلسلة أفلام Iron Man؟", "options": ["ستيف روجرز", "توني ستارك", "بروس وين", "كلارك كنت"], "answer": "توني ستارك"},
                {"q": "في أي مدينة تدور أحداث فيلم Casablanca؟", "options": ["القاهرة", "تونس", "الدار البيضاء", "بيروت"], "answer": "الدار البيضاء"},
                {"q": "ما اسم الأسد في فيلم The Lion King؟", "options": ["موفاسا", "سيمبا", "أكيلي", "بانزاي"], "answer": "سيمبا"},
                {"q": "من صوّت شخصية Shrek؟", "options": ["جيم كاري", "مايك مايرز", "آدم ساندلر", "وِل سميث"], "answer": "مايك مايرز"},
                {"q": "ما اسم الجزيرة في فيلم Jurassic Park؟", "options": ["جزيرة النار", "إيسلا نوبلار", "جزيرة الديناصورات", "إيسلا سورنا"], "answer": "إيسلا نوبلار"},
                {"q": "كم جزءاً في سلسلة أفلام Fast and Furious حتى 2023؟", "options": ["8", "9", "10", "11"], "answer": "10"},
                {"q": "من لعب دور جاك في فيلم Titanic؟", "options": ["براد بيت", "ليوناردو دي كابريو", "توم هانكس", "جوني ديب"], "answer": "ليوناردو دي كابريو"},
                {"q": "ما اسم الساحر في فيلم Harry Potter؟", "options": ["هرميون", "رون", "هاري بوتر", "نيفيل"], "answer": "هاري بوتر"},
                {"q": "في أي مدينة تدور أحداث فيلم The Dark Knight؟", "options": ["نيويورك", "جوثام", "متروبوليس", "شيكاغو"], "answer": "جوثام"},
            ],
            "medium": [
                {"q": "كم جزءاً يحتوي فيلم The Lord of the Rings؟", "options": ["2", "3", "4", "5"], "answer": "3"},
                {"q": "من لعب دور جوكر في Dark Knight؟", "options": ["جاك نيكلسون", "خواكين فينيكس", "هيث ليدجر", "جاريد ليتو"], "answer": "هيث ليدجر"},
                {"q": "في أي عام صدر فيلم Avatar الأول؟", "options": ["2007", "2008", "2009", "2010"], "answer": "2009"},
                {"q": "من أخرج سلسلة أفلام The Godfather؟", "options": ["مارتن سكورسيزي", "فرانسيس فورد كوبولا", "ريدلي سكوت", "سيدني لوميت"], "answer": "فرانسيس فورد كوبولا"},
                {"q": "ما أعلى إيراد فيلم في التاريخ حتى 2023؟", "options": ["Titanic", "Avengers Endgame", "Avatar", "Star Wars"], "answer": "Avatar"},
                {"q": "من أخرج فيلم Inception؟", "options": ["ستيفن سبيلبرغ", "كريستوفر نولان", "جيمس كاميرون", "ريدلي سكوت"], "answer": "كريستوفر نولان"},
                {"q": "في أي عام صدر أول فيلم Marvel في عالم MCU؟", "options": ["2006", "2007", "2008", "2009"], "answer": "2008"},
                {"q": "من لعب دور ثانوس في أفلام Avengers؟", "options": ["جوش برولين", "بريدجر فوندا", "بين كينغسلي", "جيف بريدجز"], "answer": "جوش برولين"},
                {"q": "ما اسم الجزء الأول من سلسلة Matrix؟", "options": ["The Matrix Reloaded", "The Matrix", "The Matrix Revolutions", "Matrix Resurrections"], "answer": "The Matrix"},
                {"q": "من أخرج فيلم Schindler's List؟", "options": ["مارتن سكورسيزي", "ستانلي كوبريك", "ستيفن سبيلبرغ", "وودي آلن"], "answer": "ستيفن سبيلبرغ"},
            ],
            "hard": [
                {"q": "من كتب رواية The Godfather؟", "options": ["ماريو بوزو", "ستيفن كينج", "جون غريشام", "توم كلانسي"], "answer": "ماريو بوزو"},
                {"q": "كم حصد فيلم Titanic من جوائز الأوسكار؟", "options": ["9", "10", "11", "14"], "answer": "11"},
                {"q": "ما اسم المخرج الياباني صاحب فيلم Spirited Away؟", "options": ["أكيرا كوروساوا", "هاياو ميازاكي", "ماكوتو شينكاي", "ساتوشي كون"], "answer": "هاياو ميازاكي"},
                {"q": "في أي عام حصل فيلم Parasite على أوسكار أفضل فيلم؟", "options": ["2018", "2019", "2020", "2021"], "answer": "2020"},
                {"q": "من أخرج فيلم 2001: A Space Odyssey؟", "options": ["ريدلي سكوت", "ستيفن سبيلبرغ", "ستانلي كوبريك", "جورج لوكاس"], "answer": "ستانلي كوبريك"},
                {"q": "ما أول فيلم ناطق في التاريخ؟", "options": ["Gone with the Wind", "The Jazz Singer", "Metropolis", "Sunrise"], "answer": "The Jazz Singer"},
                {"q": "من فاز بأوسكار أفضل مخرج عن فيلم The Revenant؟", "options": ["كريستوفر نولان", "أليخاندرو إيناريتو", "مارتن سكورسيزي", "كوينتن تارانتينو"], "answer": "أليخاندرو إيناريتو"},
                {"q": "ما اسم شركة الإنتاج التي أسسها ستيفن سبيلبرغ؟", "options": ["Miramax", "DreamWorks", "Lionsgate", "A24"], "answer": "DreamWorks"},
                {"q": "كم فيلماً أخرج ستانلي كوبريك في مسيرته؟", "options": ["10", "13", "16", "20"], "answer": "13"},
                {"q": "من كتب موسيقى معظم أفلام ستيفن سبيلبرغ؟", "options": ["هانز زيمر", "جون ويليامز", "إنيو موريكوني", "داني إلفمان"], "answer": "جون ويليامز"},
            ],
        },
        "general": {
            "easy": [
                {"q": "ما عاصمة فرنسا؟", "options": ["لندن", "برلين", "باريس", "روما"], "answer": "باريس"},
                {"q": "كم عدد أيام السنة؟", "options": ["354", "360", "365", "366"], "answer": "365"},
                {"q": "ما أكبر كوكب في المجموعة الشمسية؟", "options": ["زحل", "المشتري", "أورانوس", "نبتون"], "answer": "المشتري"},
                {"q": "ما لون السماء في الطقس الصافي؟", "options": ["أخضر", "أزرق", "أصفر", "بنفسجي"], "answer": "أزرق"},
                {"q": "كم يوماً في أسبوع؟", "options": ["5", "6", "7", "8"], "answer": "7"},
                {"q": "ما أسرع حيوان بري في العالم؟", "options": ["الأسد", "الفهد", "الحصان", "الغزال"], "answer": "الفهد"},
                {"q": "ما عاصمة المملكة العربية السعودية؟", "options": ["جدة", "مكة", "الرياض", "المدينة"], "answer": "الرياض"},
                {"q": "كم عدد أصابع اليد؟", "options": ["4", "5", "6", "10"], "answer": "5"},
                {"q": "ما أكبر محيط في العالم؟", "options": ["الأطلسي", "الهندي", "الهادئ", "المتجمد"], "answer": "الهادئ"},
                {"q": "ما عاصمة مصر؟", "options": ["الإسكندرية", "الجيزة", "القاهرة", "الأقصر"], "answer": "القاهرة"},
            ],
            "medium": [
                {"q": "من اخترع الهاتف؟", "options": ["توماس إديسون", "ألكسندر غراهام بيل", "نيكولا تسلا", "ماركوني"], "answer": "ألكسندر غراهام بيل"},
                {"q": "ما أطول نهر في العالم؟", "options": ["الأمازون", "النيل", "المسيسيبي", "اليانغتسي"], "answer": "النيل"},
                {"q": "كم عدد قارات العالم؟", "options": ["5", "6", "7", "8"], "answer": "7"},
                {"q": "ما العنصر الأكثر وفرة في الغلاف الجوي؟", "options": ["الأكسجين", "النيتروجين", "ثاني أكسيد الكربون", "الهيدروجين"], "answer": "النيتروجين"},
                {"q": "كم كيلومتراً يبلغ محيط الأرض تقريباً؟", "options": ["30,000", "40,075", "50,000", "60,000"], "answer": "40,075"},
                {"q": "ما أعمق نقطة في المحيطات؟", "options": ["خندق بورتوريكو", "خندق تونغا", "خندق ماريانا", "خندق جاوة"], "answer": "خندق ماريانا"},
                {"q": "من اخترع المصباح الكهربائي؟", "options": ["نيكولا تسلا", "ألكسندر بيل", "توماس إديسون", "بنيامين فرانكلين"], "answer": "توماس إديسون"},
                {"q": "كم دولة تشترك في قارة أمريكا الجنوبية؟", "options": ["10", "12", "14", "16"], "answer": "12"},
                {"q": "ما أطول سور في العالم؟", "options": ["سور الهند", "سور الصين العظيم", "سور أوريليان", "سور أدريان"], "answer": "سور الصين العظيم"},
                {"q": "كم كوكباً في مجموعتنا الشمسية؟", "options": ["7", "8", "9", "10"], "answer": "8"},
            ],
            "hard": [
                {"q": "في أي عام اكتشف الإنسان أمريكا؟", "options": ["1390", "1492", "1500", "1520"], "answer": "1492"},
                {"q": "ما العنصر الكيميائي الذي رمزه Au؟", "options": ["الفضة", "الذهب", "النحاس", "الحديد"], "answer": "الذهب"},
                {"q": "من هو مؤسس شركة Apple؟", "options": ["بيل غيتس", "ستيف جوبز", "إيلون ماسك", "مارك زوكربرغ"], "answer": "ستيف جوبز"},
                {"q": "ما اسم النظرية التي وضعها أينشتاين؟", "options": ["نظرية الكم", "النسبية العامة", "نظرية الأوتار", "نظرية الانفجار الكبير"], "answer": "النسبية العامة"},
                {"q": "ما عدد العناصر في الجدول الدوري حتى 2023؟", "options": ["108", "114", "118", "124"], "answer": "118"},
                {"q": "ما اسم أول قمر صناعي أطلقه الإنسان؟", "options": ["أبولو", "فوياجر", "سبوتنيك", "إكسبلورر"], "answer": "سبوتنيك"},
                {"q": "كم سنة ضوئية تبعد أقرب نجمة لشمسنا؟", "options": ["2.5", "4.2", "8.6", "12"], "answer": "4.2"},
                {"q": "ما اسم الجسيم الذي يُعرف بـ جسيم الله؟", "options": ["البروتون", "الإلكترون", "بوزون هيغز", "النيوترينو"], "answer": "بوزون هيغز"},
                {"q": "في أي عام اكتُشف الحمض النووي DNA؟", "options": ["1943", "1953", "1963", "1973"], "answer": "1953"},
                {"q": "ما سرعة الضوء تقريباً؟", "options": ["200,000 كم/ث", "300,000 كم/ث", "400,000 كم/ث", "500,000 كم/ث"], "answer": "300,000 كم/ث"},
            ],
        },
        "history": {
            "easy": [
                {"q": "من بنى الأهرامات؟", "options": ["الرومان", "اليونانيون", "المصريون القدماء", "الفرس"], "answer": "المصريون القدماء"},
                {"q": "في أي قرن وقعت الحرب العالمية الثانية؟", "options": ["18", "19", "20", "21"], "answer": "20"},
                {"q": "من كان أول رئيس للولايات المتحدة؟", "options": ["لنكولن", "واشنطن", "جيفرسون", "فرانكلين"], "answer": "واشنطن"},
                {"q": "ما اسم السفينة التي غرقت عام 1912؟", "options": ["أوليمبيك", "تيتانيك", "لوزيتانيا", "بريتانيك"], "answer": "تيتانيك"},
                {"q": "أي إمبراطورية كانت الأكبر في التاريخ؟", "options": ["الرومانية", "المغولية", "البريطانية", "العثمانية"], "answer": "البريطانية"},
                {"q": "من اخترع الطباعة؟", "options": ["غوتنبرغ", "فرانكلين", "إديسون", "نيوتن"], "answer": "غوتنبرغ"},
                {"q": "ما اسم الثورة الفرنسية الشهيرة؟", "options": ["1688", "1776", "1789", "1848"], "answer": "1789"},
                {"q": "من قاد ثورة أكتوبر الروسية؟", "options": ["ستالين", "تروتسكي", "لينين", "خروتشوف"], "answer": "لينين"},
                {"q": "ما اسم المعركة التي هُزم فيها نابليون نهائياً؟", "options": ["أوسترليتز", "بورودينو", "ووترلو", "لايبزيغ"], "answer": "ووترلو"},
                {"q": "في أي عام سقط جدار برلين؟", "options": ["1987", "1988", "1989", "1990"], "answer": "1989"},
            ],
            "medium": [
                {"q": "في أي عام بدأت الحرب العالمية الأولى؟", "options": ["1912", "1914", "1916", "1918"], "answer": "1914"},
                {"q": "من قاد المقاومة الفرنسية في الحرب العالمية الثانية؟", "options": ["نابليون", "ديغول", "بيتان", "كليمنصو"], "answer": "ديغول"},
                {"q": "أي حضارة بنت الكولوسيوم؟", "options": ["الإغريقية", "الرومانية", "الفارسية", "المصرية"], "answer": "الرومانية"},
                {"q": "في أي عام اكتشف كولومبوس أمريكا؟", "options": ["1488", "1492", "1498", "1502"], "answer": "1492"},
                {"q": "ما اسم أول إمبراطور صيني وحّد الصين؟", "options": ["كونفوشيوس", "تشين شي هوانغ", "هان وو دي", "ماو تسي تونغ"], "answer": "تشين شي هوانغ"},
                {"q": "في أي عام انتهت الحرب العالمية الثانية؟", "options": ["1943", "1944", "1945", "1946"], "answer": "1945"},
                {"q": "من هو الفاتح العثماني للقسطنطينية؟", "options": ["سليمان القانوني", "محمد الثاني", "سليم الأول", "بايزيد الثاني"], "answer": "محمد الثاني"},
                {"q": "ما اسم المعاهدة التي أنهت الحرب العالمية الأولى؟", "options": ["معاهدة باريس", "معاهدة فرساي", "معاهدة لندن", "معاهدة فيينا"], "answer": "معاهدة فرساي"},
                {"q": "في أي دولة قامت ثورة البلاشفة؟", "options": ["ألمانيا", "النمسا", "روسيا", "المجر"], "answer": "روسيا"},
                {"q": "من هو أول إنسان يمشي على سطح القمر؟", "options": ["باز ألدرين", "نيل أرمسترونغ", "يوري غاغارين", "جون غلين"], "answer": "نيل أرمسترونغ"},
            ],
            "hard": [
                {"q": "في أي عام فتح صلاح الدين الأيوبي القدس؟", "options": ["1185", "1187", "1190", "1192"], "answer": "1187"},
                {"q": "من كتب كتاب الأمير؟", "options": ["أرسطو", "أفلاطون", "ميكيافيلي", "هوبز"], "answer": "ميكيافيلي"},
                {"q": "في أي عام تأسست الأمم المتحدة؟", "options": ["1943", "1945", "1947", "1950"], "answer": "1945"},
                {"q": "ما اسم أول حرب في التاريخ الموثقة؟", "options": ["حرب طروادة", "معركة قادش", "حرب الپيلوبونيز", "حرب الخلافة"], "answer": "معركة قادش"},
                {"q": "من هو مؤسس الإمبراطورية المغولية؟", "options": ["كوبلاي خان", "تيمورلنك", "جنكيز خان", "هولاكو"], "answer": "جنكيز خان"},
                {"q": "في أي عام أُلغي نظام الرق في الولايات المتحدة؟", "options": ["1860", "1863", "1865", "1870"], "answer": "1865"},
                {"q": "ما اسم الإمبراطور الروماني الذي اعتنق المسيحية؟", "options": ["نيرون", "ماركوس أوريليوس", "قسطنطين", "ديوكليتيان"], "answer": "قسطنطين"},
                {"q": "في أي عام بدأ الاستعمار الأوروبي لأفريقيا رسمياً بمؤتمر برلين؟", "options": ["1880", "1884", "1890", "1895"], "answer": "1884"},
                {"q": "من هو مؤسس الدولة العثمانية؟", "options": ["أرطغرل", "عثمان الأول", "أورخان", "مراد الأول"], "answer": "عثمان الأول"},
                {"q": "في أي عام اخترع الإنسان الكتابة تقريباً؟", "options": ["5000 ق.م", "3500 ق.م", "2000 ق.م", "1000 ق.م"], "answer": "3500 ق.م"},
            ],
        },
        "geography": {
            "easy": [
                {"q": "ما أكبر دولة في العالم مساحةً؟", "options": ["الصين", "الولايات المتحدة", "كندا", "روسيا"], "answer": "روسيا"},
                {"q": "ما عاصمة اليابان؟", "options": ["أوساكا", "طوكيو", "كيوتو", "هيروشيما"], "answer": "طوكيو"},
                {"q": "على أي قارة تقع مصر؟", "options": ["آسيا", "أوروبا", "أفريقيا", "أمريكا"], "answer": "أفريقيا"},
                {"q": "ما عاصمة البرازيل؟", "options": ["ساو باولو", "ريو دي جانيرو", "برازيليا", "سالفادور"], "answer": "برازيليا"},
                {"q": "ما أكبر دولة عربية مساحةً؟", "options": ["مصر", "السعودية", "الجزائر", "السودان"], "answer": "الجزائر"},
                {"q": "أي بحر يفصل أوروبا عن أفريقيا؟", "options": ["البحر الأحمر", "بحر العرب", "البحر المتوسط", "بحر الشمال"], "answer": "البحر المتوسط"},
                {"q": "ما عاصمة أستراليا؟", "options": ["سيدني", "ملبورن", "كانبيرا", "بريسبان"], "answer": "كانبيرا"},
                {"q": "ما أصغر دولة في العالم؟", "options": ["موناكو", "سان مارينو", "الفاتيكان", "ليختنشتاين"], "answer": "الفاتيكان"},
                {"q": "على أي قارة تقع الأرجنتين؟", "options": ["أمريكا الشمالية", "أمريكا الجنوبية", "أوروبا", "أفريقيا"], "answer": "أمريكا الجنوبية"},
                {"q": "ما عاصمة كندا؟", "options": ["تورنتو", "مونتريال", "فانكوفر", "أوتاوا"], "answer": "أوتاوا"},
            ],
            "medium": [
                {"q": "ما أعلى جبل في العالم؟", "options": ["كي 2", "إيفرست", "كيليمنجارو", "ماكينلي"], "answer": "إيفرست"},
                {"q": "كم عدد دول العالم تقريباً؟", "options": ["150", "175", "195", "210"], "answer": "195"},
                {"q": "ما أطول نهر في آسيا؟", "options": ["الغانج", "اليانغتسي", "الميكونغ", "الأوب"], "answer": "اليانغتسي"},
                {"q": "في أي قارة تقع جبال الأنديز؟", "options": ["أمريكا الشمالية", "أمريكا الجنوبية", "أفريقيا", "آسيا"], "answer": "أمريكا الجنوبية"},
                {"q": "ما أكبر صحراء في العالم؟", "options": ["صحراء الصحراء الكبرى", "صحراء جوبي", "صحراء أنتاركتيكا", "صحراء ربع الخالي"], "answer": "صحراء أنتاركتيكا"},
                {"q": "ما عدد الدول التي تشترك في الحدود مع روسيا؟", "options": ["12", "14", "16", "18"], "answer": "14"},
                {"q": "أي بلد يُعرف بأرض الشمس المشرقة؟", "options": ["الصين", "كوريا", "اليابان", "تايلاند"], "answer": "اليابان"},
                {"q": "ما أعمق بحيرة في العالم؟", "options": ["بحيرة فيكتوريا", "بحيرة بايكال", "بحيرة تيتيكاكا", "بحيرة سوبيريور"], "answer": "بحيرة بايكال"},
                {"q": "ما اسم المضيق الذي يفصل أمريكا عن روسيا؟", "options": ["مضيق هرمز", "مضيق ملقا", "مضيق بيرينغ", "مضيق جبل طارق"], "answer": "مضيق بيرينغ"},
                {"q": "في أي قارة يقع معظم الأمازون؟", "options": ["أمريكا الوسطى", "أمريكا الشمالية", "أمريكا الجنوبية", "أفريقيا"], "answer": "أمريكا الجنوبية"},
            ],
            "hard": [
                {"q": "ما أبعد نقطة مأهولة عن اليابسة في العالم؟", "options": ["جزيرة ترستان دا كونا", "نقطة نيمو", "جزيرة بووفيت", "جزيرة هيرد"], "answer": "نقطة نيمو"},
                {"q": "أي نهر يمر عبر أكبر عدد من الدول؟", "options": ["النيل", "الأمازون", "الدانوب", "الراين"], "answer": "الدانوب"},
                {"q": "ما ارتفاع جبل إيفرست بالضبط؟", "options": ["8,444م", "8,849م", "8,611م", "8,516م"], "answer": "8,849م"},
                {"q": "ما أكثر دولة مكتظة بالسكان في أفريقيا؟", "options": ["مصر", "إثيوبيا", "نيجيريا", "جنوب أفريقيا"], "answer": "نيجيريا"},
                {"q": "كم طول نهر النيل تقريباً؟", "options": ["5,500 كم", "6,650 كم", "7,200 كم", "8,000 كم"], "answer": "6,650 كم"},
                {"q": "ما اسم أعلى بركان في العالم؟", "options": ["فيزوف", "إيتنا", "أوخوس ديل سالادو", "ماونا لوا"], "answer": "أوخوس ديل سالادو"},
                {"q": "في أي دولة تقع أرخبيل المالديف؟", "options": ["الهند", "سريلانكا", "المالديف نفسها", "إندونيسيا"], "answer": "المالديف نفسها"},
                {"q": "ما اسم البحيرة التي تشترك فيها 5 دول في أمريكا الشمالية؟", "options": ["البحيرات العظمى", "بحيرة بايكال", "بحيرة تشاد", "بحيرة فيكتوريا"], "answer": "البحيرات العظمى"},
                {"q": "ما أطول جبال في أفريقيا؟", "options": ["جبال الأطلس", "جبال دراكنزبرغ", "جبال روينزوري", "جبال إثيوبيا"], "answer": "جبال الأطلس"},
                {"q": "كم عدد الدول التي لا ساحل بحري لها في أفريقيا؟", "options": ["12", "14", "16", "18"], "answer": "16"},
            ],
        },
    },
    "en": {
        "sports": {
            "easy": [
                {"q": "How many players are in a football team?", "options": ["9", "10", "11", "12"], "answer": "11"},
                {"q": "Which country hosted the 2022 World Cup?", "options": ["UAE", "Qatar", "Saudi Arabia", "Bahrain"], "answer": "Qatar"},
                {"q": "How many minutes in a football match?", "options": ["80", "90", "100", "120"], "answer": "90"},
                {"q": "What sport is played at Wimbledon?", "options": ["Golf", "Tennis", "Cricket", "Rugby"], "answer": "Tennis"},
                {"q": "How many players in a basketball team on court?", "options": ["4", "5", "6", "7"], "answer": "5"},
                {"q": "What is the diameter of a basketball hoop?", "options": ["40cm", "45cm", "50cm", "55cm"], "answer": "45cm"},
                {"q": "How many sets in a tennis Grand Slam men's final?", "options": ["3", "4", "5", "6"], "answer": "5"},
                {"q": "What color is the center court at Wimbledon?", "options": ["Clay red", "Hard blue", "Green grass", "Indoor wood"], "answer": "Green grass"},
                {"q": "How many holes in a round of golf?", "options": ["9", "12", "18", "24"], "answer": "18"},
                {"q": "What sport uses a puck?", "options": ["Baseball", "Ice hockey", "Lacrosse", "Cricket"], "answer": "Ice hockey"},
            ],
            "medium": [
                {"q": "Who won the 2018 World Cup?", "options": ["Germany", "Brazil", "France", "Argentina"], "answer": "France"},
                {"q": "How many times has Brazil won the World Cup?", "options": ["3", "4", "5", "6"], "answer": "5"},
                {"q": "Who is the all-time top scorer in football?", "options": ["Ronaldo", "Messi", "Pele", "Maradona"], "answer": "Ronaldo"},
                {"q": "Who won the Champions League in 2023?", "options": ["Real Madrid", "Manchester City", "Barcelona", "Bayern"], "answer": "Manchester City"},
                {"q": "Which country won the most Olympic gold medals in 2020?", "options": ["China", "USA", "UK", "Japan"], "answer": "USA"},
                {"q": "Who holds the record for most Grand Slam titles in men's tennis?", "options": ["Federer", "Nadal", "Djokovic", "Sampras"], "answer": "Djokovic"},
                {"q": "Which NBA team has the most championships?", "options": ["Chicago Bulls", "LA Lakers", "Boston Celtics", "Golden State Warriors"], "answer": "Boston Celtics"},
                {"q": "Who won the 2022 FIFA World Cup?", "options": ["France", "Brazil", "Argentina", "Morocco"], "answer": "Argentina"},
                {"q": "Which sport uses a shuttlecock?", "options": ["Tennis", "Squash", "Badminton", "Pickleball"], "answer": "Badminton"},
                {"q": "How many players are on a baseball team?", "options": ["7", "8", "9", "10"], "answer": "9"},
            ],
            "hard": [
                {"q": "In which year was Real Madrid founded?", "options": ["1900", "1902", "1905", "1910"], "answer": "1902"},
                {"q": "Who has won the most Ballon d'Or awards?", "options": ["Ronaldo", "Messi", "Neymar", "Mbappe"], "answer": "Messi"},
                {"q": "How many teams in the 2026 World Cup?", "options": ["32", "36", "48", "64"], "answer": "48"},
                {"q": "Who scored the famous Hand of God goal?", "options": ["Pele", "Ronaldo", "Maradona", "Zidane"], "answer": "Maradona"},
                {"q": "Which country hosted the first modern Olympics?", "options": ["France", "UK", "Greece", "USA"], "answer": "Greece"},
                {"q": "Who was the first player to score 100 goals in international football?", "options": ["Messi", "Ronaldo", "Ali Daei", "Mokhtar Dahari"], "answer": "Ali Daei"},
                {"q": "How many times has Novak Djokovic won Wimbledon?", "options": ["5", "6", "7", "8"], "answer": "7"},
                {"q": "Which club did Pele spend most of his career at?", "options": ["Flamengo", "Santos", "Corinthians", "New York Cosmos"], "answer": "Santos"},
                {"q": "In what year was the first Super Bowl played?", "options": ["1965", "1967", "1969", "1971"], "answer": "1967"},
                {"q": "Who holds the record for fastest 100m sprint?", "options": ["Asafa Powell", "Tyson Gay", "Usain Bolt", "Justin Gatlin"], "answer": "Usain Bolt"},
            ],
        },
        "movies": {
            "easy": [
                {"q": "Who directed Titanic?", "options": ["Spielberg", "James Cameron", "Nolan", "Tim Burton"], "answer": "James Cameron"},
                {"q": "What is Iron Man's real name?", "options": ["Steve Rogers", "Tony Stark", "Bruce Wayne", "Clark Kent"], "answer": "Tony Stark"},
                {"q": "Who voiced Shrek?", "options": ["Jim Carrey", "Mike Myers", "Adam Sandler", "Will Smith"], "answer": "Mike Myers"},
                {"q": "What is the name of the lion cub in The Lion King?", "options": ["Mufasa", "Simba", "Akili", "Pumbaa"], "answer": "Simba"},
                {"q": "Who played Jack in Titanic?", "options": ["Brad Pitt", "Leonardo DiCaprio", "Tom Hanks", "Johnny Depp"], "answer": "Leonardo DiCaprio"},
                {"q": "What city is Gotham City based on?", "options": ["Los Angeles", "Chicago", "New York", "Boston"], "answer": "New York"},
                {"q": "How many films are in the original Star Wars trilogy?", "options": ["2", "3", "4", "6"], "answer": "3"},
                {"q": "Who plays Harry Potter in the film series?", "options": ["Rupert Grint", "Daniel Radcliffe", "Tom Felton", "Matthew Lewis"], "answer": "Daniel Radcliffe"},
                {"q": "What studio made Toy Story?", "options": ["Disney", "DreamWorks", "Pixar", "Universal"], "answer": "Pixar"},
                {"q": "Who directed The Dark Knight?", "options": ["Tim Burton", "Joel Schumacher", "Christopher Nolan", "Zack Snyder"], "answer": "Christopher Nolan"},
            ],
            "medium": [
                {"q": "How many parts does Lord of the Rings have?", "options": ["2", "3", "4", "5"], "answer": "3"},
                {"q": "Who played the Joker in The Dark Knight?", "options": ["Jack Nicholson", "Joaquin Phoenix", "Heath Ledger", "Jared Leto"], "answer": "Heath Ledger"},
                {"q": "In what year was the first Avatar released?", "options": ["2007", "2008", "2009", "2010"], "answer": "2009"},
                {"q": "Who directed Inception?", "options": ["Spielberg", "Christopher Nolan", "James Cameron", "Ridley Scott"], "answer": "Christopher Nolan"},
                {"q": "Which film has the highest box office of all time?", "options": ["Titanic", "Avengers Endgame", "Avatar", "Star Wars"], "answer": "Avatar"},
                {"q": "Who plays Thanos in Avengers?", "options": ["Josh Brolin", "Bridger Fonda", "Ben Kingsley", "Jeff Bridges"], "answer": "Josh Brolin"},
                {"q": "In what year was the first MCU film released?", "options": ["2006", "2007", "2008", "2009"], "answer": "2008"},
                {"q": "Who directed Schindler's List?", "options": ["Martin Scorsese", "Stanley Kubrick", "Steven Spielberg", "Woody Allen"], "answer": "Steven Spielberg"},
                {"q": "What film won Best Picture at the Oscars in 2020?", "options": ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"], "answer": "Parasite"},
                {"q": "Who directed Pulp Fiction?", "options": ["Martin Scorsese", "Quentin Tarantino", "Coen Brothers", "David Fincher"], "answer": "Quentin Tarantino"},
            ],
            "hard": [
                {"q": "Who wrote the novel The Godfather?", "options": ["Mario Puzo", "Stephen King", "John Grisham", "Tom Clancy"], "answer": "Mario Puzo"},
                {"q": "How many Oscars did Titanic win?", "options": ["9", "10", "11", "14"], "answer": "11"},
                {"q": "Who directed Spirited Away?", "options": ["Kurosawa", "Hayao Miyazaki", "Makoto Shinkai", "Satoshi Kon"], "answer": "Hayao Miyazaki"},
                {"q": "Who composed the music for most Spielberg films?", "options": ["Hans Zimmer", "John Williams", "Ennio Morricone", "Danny Elfman"], "answer": "John Williams"},
                {"q": "In what year was the first sound film released?", "options": ["1920", "1923", "1927", "1930"], "answer": "1927"},
                {"q": "Who directed 2001: A Space Odyssey?", "options": ["Ridley Scott", "Spielberg", "Stanley Kubrick", "George Lucas"], "answer": "Stanley Kubrick"},
                {"q": "Which film won the first Academy Award for Best Picture?", "options": ["Wings", "Sunrise", "The Broadway Melody", "All Quiet on the Western Front"], "answer": "Wings"},
                {"q": "How many films did Stanley Kubrick direct?", "options": ["10", "13", "16", "20"], "answer": "13"},
                {"q": "Who directed Parasite?", "options": ["Park Chan-wook", "Lee Chang-dong", "Bong Joon-ho", "Kim Ki-duk"], "answer": "Bong Joon-ho"},
                {"q": "What production company did Steven Spielberg co-found?", "options": ["Miramax", "DreamWorks", "Lionsgate", "A24"], "answer": "DreamWorks"},
            ],
        },
        "general": {
            "easy": [
                {"q": "What is the capital of France?", "options": ["London", "Berlin", "Paris", "Rome"], "answer": "Paris"},
                {"q": "How many days are in a year?", "options": ["354", "360", "365", "366"], "answer": "365"},
                {"q": "What is the largest planet in our solar system?", "options": ["Saturn", "Jupiter", "Uranus", "Neptune"], "answer": "Jupiter"},
                {"q": "What is the fastest land animal?", "options": ["Lion", "Cheetah", "Horse", "Gazelle"], "answer": "Cheetah"},
                {"q": "How many colors are in a rainbow?", "options": ["5", "6", "7", "8"], "answer": "7"},
                {"q": "What is the largest ocean?", "options": ["Atlantic", "Indian", "Pacific", "Arctic"], "answer": "Pacific"},
                {"q": "How many continents are there?", "options": ["5", "6", "7", "8"], "answer": "7"},
                {"q": "What is the capital of Japan?", "options": ["Osaka", "Tokyo", "Kyoto", "Hiroshima"], "answer": "Tokyo"},
                {"q": "How many sides does a hexagon have?", "options": ["5", "6", "7", "8"], "answer": "6"},
                {"q": "What gas do plants absorb?", "options": ["Oxygen", "Nitrogen", "CO2", "Hydrogen"], "answer": "CO2"},
            ],
            "medium": [
                {"q": "Who invented the telephone?", "options": ["Edison", "Alexander Graham Bell", "Tesla", "Marconi"], "answer": "Alexander Graham Bell"},
                {"q": "What is the longest river in the world?", "options": ["Amazon", "Nile", "Mississippi", "Yangtze"], "answer": "Nile"},
                {"q": "What is the most abundant gas in Earth's atmosphere?", "options": ["Oxygen", "Nitrogen", "CO2", "Hydrogen"], "answer": "Nitrogen"},
                {"q": "Who invented the light bulb?", "options": ["Tesla", "Bell", "Edison", "Franklin"], "answer": "Edison"},
                {"q": "What is the circumference of the Earth?", "options": ["30,000 km", "40,075 km", "50,000 km", "60,000 km"], "answer": "40,075 km"},
                {"q": "What is the deepest point in the ocean?", "options": ["Puerto Rico Trench", "Tonga Trench", "Mariana Trench", "Java Trench"], "answer": "Mariana Trench"},
                {"q": "How many bones are in the adult human body?", "options": ["186", "206", "226", "246"], "answer": "206"},
                {"q": "How many planets are in our solar system?", "options": ["7", "8", "9", "10"], "answer": "8"},
                {"q": "Who founded Apple?", "options": ["Bill Gates", "Steve Jobs", "Elon Musk", "Mark Zuckerberg"], "answer": "Steve Jobs"},
                {"q": "What is the chemical symbol for gold?", "options": ["Ag", "Au", "Cu", "Fe"], "answer": "Au"},
            ],
            "hard": [
                {"q": "In what year was America discovered by Columbus?", "options": ["1390", "1492", "1500", "1520"], "answer": "1492"},
                {"q": "What theory did Einstein propose?", "options": ["Quantum Theory", "General Relativity", "String Theory", "Big Bang"], "answer": "General Relativity"},
                {"q": "How many elements are in the periodic table?", "options": ["108", "114", "118", "124"], "answer": "118"},
                {"q": "What was the name of the first artificial satellite?", "options": ["Apollo", "Voyager", "Sputnik", "Explorer"], "answer": "Sputnik"},
                {"q": "How many light years away is the nearest star?", "options": ["2.5", "4.2", "8.6", "12"], "answer": "4.2"},
                {"q": "What particle is known as the God particle?", "options": ["Proton", "Electron", "Higgs Boson", "Neutrino"], "answer": "Higgs Boson"},
                {"q": "In what year was DNA discovered?", "options": ["1943", "1953", "1963", "1973"], "answer": "1953"},
                {"q": "What is the speed of light?", "options": ["200,000 km/s", "300,000 km/s", "400,000 km/s", "500,000 km/s"], "answer": "300,000 km/s"},
                {"q": "What is the atomic number of Carbon?", "options": ["4", "6", "8", "12"], "answer": "6"},
                {"q": "Which scientist proposed the heliocentric model of the solar system?", "options": ["Galileo", "Kepler", "Copernicus", "Newton"], "answer": "Copernicus"},
            ],
        },
        "history": {
            "easy": [
                {"q": "Who built the Pyramids?", "options": ["Romans", "Greeks", "Ancient Egyptians", "Persian Pharaohs"], "answer": "Ancient Egyptians"},
                {"q": "In which century did World War II occur?", "options": ["18th", "19th", "20th", "21st"], "answer": "20th"},
                {"q": "Who was the first US President?", "options": ["Lincoln", "Washington", "Jefferson", "Franklin"], "answer": "Washington"},
                {"q": "What ship sank in 1912?", "options": ["Olympic", "Titanic", "Lusitania", "Britannic"], "answer": "Titanic"},
                {"q": "Who led the Russian Revolution?", "options": ["Stalin", "Trotsky", "Lenin", "Khrushchev"], "answer": "Lenin"},
                {"q": "In what year did the Berlin Wall fall?", "options": ["1987", "1988", "1989", "1990"], "answer": "1989"},
                {"q": "Who invented the printing press?", "options": ["Gutenberg", "Franklin", "Edison", "Newton"], "answer": "Gutenberg"},
                {"q": "Which battle was Napoleon's final defeat?", "options": ["Austerlitz", "Borodino", "Waterloo", "Leipzig"], "answer": "Waterloo"},
                {"q": "Which civilization built the Colosseum?", "options": ["Greek", "Roman", "Persian", "Egyptian"], "answer": "Roman"},
                {"q": "In what year did World War I begin?", "options": ["1912", "1914", "1916", "1918"], "answer": "1914"},
            ],
            "medium": [
                {"q": "In what year did Columbus discover America?", "options": ["1488", "1492", "1498", "1502"], "answer": "1492"},
                {"q": "Who was the first Emperor to unify China?", "options": ["Confucius", "Qin Shi Huang", "Han Wudi", "Mao"], "answer": "Qin Shi Huang"},
                {"q": "In what year did World War II end?", "options": ["1943", "1944", "1945", "1946"], "answer": "1945"},
                {"q": "Who was the Ottoman conqueror of Constantinople?", "options": ["Suleiman", "Mehmed II", "Selim I", "Bayezid II"], "answer": "Mehmed II"},
                {"q": "What treaty ended World War I?", "options": ["Treaty of Paris", "Treaty of Versailles", "Treaty of London", "Treaty of Vienna"], "answer": "Treaty of Versailles"},
                {"q": "Who was the first human in space?", "options": ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"], "answer": "Yuri Gagarin"},
                {"q": "In what year was the United Nations founded?", "options": ["1943", "1945", "1947", "1950"], "answer": "1945"},
                {"q": "Who led French resistance in WWII?", "options": ["Napoleon", "De Gaulle", "Petain", "Clemenceau"], "answer": "De Gaulle"},
                {"q": "When was the French Revolution?", "options": ["1688", "1776", "1789", "1848"], "answer": "1789"},
                {"q": "Who was the first person to walk on the Moon?", "options": ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"], "answer": "Neil Armstrong"},
            ],
            "hard": [
                {"q": "In what year did Saladin liberate Jerusalem?", "options": ["1185", "1187", "1190", "1192"], "answer": "1187"},
                {"q": "Who wrote The Prince?", "options": ["Aristotle", "Plato", "Machiavelli", "Hobbes"], "answer": "Machiavelli"},
                {"q": "Who founded the Mongol Empire?", "options": ["Kublai Khan", "Timur", "Genghis Khan", "Hulagu"], "answer": "Genghis Khan"},
                {"q": "In what year was slavery abolished in the USA?", "options": ["1860", "1863", "1865", "1870"], "answer": "1865"},
                {"q": "Which Roman Emperor converted to Christianity?", "options": ["Nero", "Marcus Aurelius", "Constantine", "Diocletian"], "answer": "Constantine"},
                {"q": "In what year was the Berlin Conference on Africa?", "options": ["1880", "1884", "1890", "1895"], "answer": "1884"},
                {"q": "Who founded the Ottoman Empire?", "options": ["Ertugrul", "Osman I", "Orhan", "Murad I"], "answer": "Osman I"},
                {"q": "When did humans first develop writing?", "options": ["5000 BC", "3500 BC", "2000 BC", "1000 BC"], "answer": "3500 BC"},
                {"q": "Which empire was the largest in history?", "options": ["Roman", "Mongol", "British", "Ottoman"], "answer": "British"},
                {"q": "Who was the last Tsar of Russia?", "options": ["Alexander III", "Nicholas II", "Alexander II", "Paul I"], "answer": "Nicholas II"},
            ],
        },
        "geography": {
            "easy": [
                {"q": "What is the largest country by area?", "options": ["China", "USA", "Canada", "Russia"], "answer": "Russia"},
                {"q": "What is the capital of Japan?", "options": ["Osaka", "Tokyo", "Kyoto", "Hiroshima"], "answer": "Tokyo"},
                {"q": "On which continent is Egypt?", "options": ["Asia", "Europe", "Africa", "America"], "answer": "Africa"},
                {"q": "What is the capital of Brazil?", "options": ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador"], "answer": "Brasilia"},
                {"q": "Which sea separates Europe from Africa?", "options": ["Red Sea", "Arabian Sea", "Mediterranean", "North Sea"], "answer": "Mediterranean"},
                {"q": "What is the capital of Australia?", "options": ["Sydney", "Melbourne", "Canberra", "Brisbane"], "answer": "Canberra"},
                {"q": "What is the smallest country in the world?", "options": ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], "answer": "Vatican City"},
                {"q": "What is the capital of Canada?", "options": ["Toronto", "Montreal", "Vancouver", "Ottawa"], "answer": "Ottawa"},
                {"q": "On which continent is Argentina?", "options": ["North America", "South America", "Europe", "Africa"], "answer": "South America"},
                {"q": "What is the capital of Germany?", "options": ["Munich", "Hamburg", "Frankfurt", "Berlin"], "answer": "Berlin"},
            ],
            "medium": [
                {"q": "What is the highest mountain in the world?", "options": ["K2", "Everest", "Kilimanjaro", "McKinley"], "answer": "Everest"},
                {"q": "Approximately how many countries are there?", "options": ["150", "175", "195", "210"], "answer": "195"},
                {"q": "What is the longest river in Asia?", "options": ["Ganges", "Yangtze", "Mekong", "Ob"], "answer": "Yangtze"},
                {"q": "On which continent are the Andes mountains?", "options": ["North America", "South America", "Africa", "Asia"], "answer": "South America"},
                {"q": "What is the largest desert in the world?", "options": ["Sahara", "Gobi", "Antarctica", "Arabian"], "answer": "Antarctica"},
                {"q": "Which country is known as the Land of the Rising Sun?", "options": ["China", "Korea", "Japan", "Thailand"], "answer": "Japan"},
                {"q": "What is the deepest lake in the world?", "options": ["Victoria", "Baikal", "Titicaca", "Superior"], "answer": "Baikal"},
                {"q": "What strait separates America from Russia?", "options": ["Hormuz", "Malacca", "Bering", "Gibraltar"], "answer": "Bering"},
                {"q": "How many countries border Russia?", "options": ["12", "14", "16", "18"], "answer": "14"},
                {"q": "Which continent is mostly covered by the Amazon?", "options": ["Central America", "North America", "South America", "Africa"], "answer": "South America"},
            ],
            "hard": [
                {"q": "Which river flows through the most countries?", "options": ["Nile", "Amazon", "Danube", "Rhine"], "answer": "Danube"},
                {"q": "What is the exact height of Mount Everest?", "options": ["8,444m", "8,849m", "8,611m", "8,516m"], "answer": "8,849m"},
                {"q": "What is the most populous country in Africa?", "options": ["Egypt", "Ethiopia", "Nigeria", "South Africa"], "answer": "Nigeria"},
                {"q": "How long is the Nile river?", "options": ["5,500 km", "6,650 km", "7,200 km", "8,000 km"], "answer": "6,650 km"},
                {"q": "What is the highest volcano in the world?", "options": ["Vesuvius", "Etna", "Ojos del Salado", "Mauna Loa"], "answer": "Ojos del Salado"},
                {"q": "How many landlocked countries are in Africa?", "options": ["12", "14", "16", "18"], "answer": "16"},
                {"q": "What is the farthest point from land in the world?", "options": ["Tristan da Cunha", "Point Nemo", "Bouvet Island", "Heard Island"], "answer": "Point Nemo"},
                {"q": "Which country has the most time zones?", "options": ["USA", "Russia", "China", "France"], "answer": "France"},
                {"q": "What is the largest lake in Africa?", "options": ["Lake Chad", "Lake Tanganyika", "Lake Victoria", "Lake Malawi"], "answer": "Lake Victoria"},
                {"q": "How many countries does the Amazon river flow through?", "options": ["6", "8", "9", "12"], "answer": "9"},
            ],
        },
    },
}

def get_questions(lang, topic, level, count=10):
    q_list = questions.get(lang, {}).get(topic, {}).get(level, [])
    return random.sample(q_list, min(count, len(q_list)))
